### ISSUE TITLE
Best practice for http and https together?

### ISSUE THREAD

**Issue by danielbprice** [zsais/go-gin-prometheus#23]
I have a server which listens for http (80) and https (443), with a gin instance for each.  I'm trying to figure out how I should handle that setup with this package-- what is the best practice?

What I _think_ I want is a single Prometheus /metrics endpoint on a separate port (let's say 3000) which exports metrics for both http and https endpoints, ideally as separate metrics sets, but merged would be OK.  Is this possible?  I couldn't find a way to get this to work, nor any examples which got to this level of detail.

The closest I got was something like this:

```
package main

import (
        "github.com/gin-gonic/gin"
        "github.com/zsais/go-gin-prometheus"
)

func main() {
        metrics := gin.New()
        r1 := gin.New()
        r2 := gin.New()

        p := ginprometheus.NewPrometheus("gin")
        p.SetListenAddressWithRouter(":3000", metrics)

        p.Use(r1)
        p.Use(r2)
        r1.GET("/", func(c *gin.Context) {
                c.JSON(200, "Hello world!")
        })
        r2.GET("/", func(c *gin.Context) {
                c.JSON(200, "Goodbye world!")
        })

        go r1.Run(":29090")
        go r2.Run(":29091")
        go metrics.Run(":3000")
}
```

Which panics as follows:

```
[GIN-debug] GET    /metrics                  --> github.com/zsais/go-gin-prometheus.prometheusHandler.func1 (3 handlers)
[GIN-debug] GET    /metrics                  --> github.com/zsais/go-gin-prometheus.prometheusHandler.func1 (3 handlers)
[GIN-debug] Listening and serving HTTP on :3000
panic: handlers are already registered for path '/metrics'

goroutine 1 [running]:
github.com/gin-gonic/gin.(*node).addRoute(0xc420070780, 0xc420024810, 0x8, 0xc42000d2c0, 0x3, 0x3)
        /home/dp/go/src/github.com/gin-gonic/gin/tree.go:235 +0x9c6
github.com/gin-gonic/gin.(*Engine).addRoute(0xc42022e480, 0xae34e2, 0x3, 0xc420024810, 0x8, 0xc42000d2c0, 0x3, 0x3)
        /home/dp/go/src/github.com/gin-gonic/gin/gin.go:252 +0x19e
github.com/gin-gonic/gin.(*RouterGroup).handle(0xc42022e480, 0xae34e2, 0x3, 0xae6ee0, 0x8, 0xc42000e188, 0x1, 0x1, 0xb68601, 0xc42000e188)
        /home/dp/go/src/github.com/gin-gonic/gin/routergroup.go:71 +0xe7
github.com/gin-gonic/gin.(*RouterGroup).GET(0xc42022e480, 0xae6ee0, 0x8, 0xc42000e188, 0x1, 0x1, 0x1, 0xb70f40)
        /home/dp/go/src/github.com/gin-gonic/gin/routergroup.go:99 +0x7c
github.com/zsais/go-gin-prometheus.(*Prometheus).setMetricsPath(0xc42023e180, 0xc42022e360)
        /home/dp/go/src/github.com/zsais/go-gin-prometheus/middleware.go:181 +0xab
github.com/zsais/go-gin-prometheus.(*Prometheus).Use(0xc42023e180, 0xc42022e360)
        /home/dp/go/src/github.com/zsais/go-gin-prometheus/middleware.go:339 +0x80
main.main()
        /home/dp/example1/main.go:16 +0xbf
```

Thanks for any ideas you might have.

**Comment by elnappo** [comment]
I did something like this:
```go
r1.Use(p.HandlerFunc())
if expose {
	p.SetMetricsPath(r1)
}
```
instead of
```go
p.Use(r1)
```

**Comment by danielbprice** [comment]
Closing, as this has had no traction for a long time, and I'm not using Gin anymore.
